Repository liquality/my-collectives-pwa, pull requests merged in 2023-11, with the labels that each got.

#36 feat: added mint nested routing and update navigation for mobile and …
  backend/src/data/seeds/seed_dev.ts
  frontend/src/App.tsx
  frontend/src/components/Challenges/ChallengeItemCard.tsx
  frontend/src/components/ConnectButton.tsx
  frontend/src/components/Header.tsx
  frontend/src/components/SideBarMenu.tsx
  frontend/src/components/TabsMenu.tsx
  frontend/src/pages/Messages.tsx
  frontend/src/pages/Mint/Challenge.tsx
  frontend/src/pages/Mint/Challenges.tsx
  frontend/src/pages/Mint/Group.tsx
  frontend/src/pages/Mint/GroupRows.tsx
  frontend/src/pages/Mint/Info.tsx
  frontend/src/pages/Mint/Messages.tsx
  frontend/src/pages/Mint/Mint.tsx
  frontend/src/theme/variables.css
Labels: 🔍 Ready for Review, size/L

#38 fix: call create user in auth, handle json better and handle unathori…
  backend/src/services/auth.ts
  frontend/src/components/Challenges/ChallengeRows.tsx
  frontend/src/hooks/useSignInWallet.ts
  frontend/src/services/ApiService.ts
  frontend/src/services/NetworkService.js
Labels: ✅ Approved, size/L

#39 Feat/discover design
  frontend/package-lock.json
  frontend/src/App.tsx
  frontend/src/components/ConnectButton.tsx
  frontend/src/components/Header.tsx
  frontend/src/components/Images/HorizontalSwipe.tsx
  frontend/src/components/Images/SwipeCard.tsx
  frontend/src/pages/Discover.tsx
  frontend/src/theme/main.css
Labels: ✅ Approved, size/L

#40 Feat/auth flow UI changes
  backend/src/services/auth.ts
  frontend/public/assets/icons/pencil.svg
  frontend/src/App.tsx
  frontend/src/hooks/useSignInWallet.ts
  frontend/src/pages/Mint/Group.tsx
  frontend/src/pages/Mint/Mint.tsx
  frontend/src/services/ApiService.ts
  frontend/src/theme/main.css
Labels: 🔍 Ready for Review, ✅ Approved, size/L

#41 add style and copytext to about page
  backend/src/index.ts
  frontend/src/pages/About.tsx
  frontend/src/pages/Discover.tsx
  frontend/src/theme/main.css
Labels: ✅ Approved, size/M

#42 Feat/custom UI
  frontend/index.html
  frontend/package.json
  frontend/public/assets/icons/discover.svg
  frontend/public/assets/icons/mint.svg
  frontend/public/assets/icons/reload.svg
  frontend/public/assets/icons/rewards.svg
  frontend/public/assets/icons/search-bar-icon.svg
  frontend/public/assets/icons/search.svg
  frontend/src/App.tsx
  frontend/src/components/Header.tsx
  frontend/src/components/PageSearchBar.tsx
  frontend/src/components/PageTopBar.tsx
  frontend/src/components/SideBarMenu.tsx
  frontend/src/components/TabsMenu.tsx
  frontend/src/hooks/useIsActiveRoute.ts
  frontend/src/pages/About.tsx
  frontend/src/pages/Discover.tsx
  frontend/src/pages/Discover/About.tsx
  frontend/src/pages/Discover/Discover.tsx
  frontend/src/pages/Discover/DiscoverTopBar.tsx
  frontend/src/pages/Discover/New.tsx
  frontend/src/pages/Mint/Group.tsx
  frontend/src/theme/main.css
  frontend/src/theme/variables.css
  frontend/vite.config.ts
Labels: ✅ Approved, size/XL

#44 Feat/no groups
  backend/src/data/migrations/20231103005059_create_table_groups.ts
  frontend/src/App.tsx
  frontend/src/components/Images/HorizontalSwipe.tsx
  frontend/src/components/Images/SwipeCard.tsx
  frontend/src/pages/Mint/CreateGroupModal.tsx
  frontend/src/pages/Mint/Mint.tsx
  frontend/src/pages/Mint/MintGroupsContent.tsx
  frontend/src/pages/Mint/NoGroups.tsx
  frontend/src/services/NetworkService.js
  frontend/src/theme/main.css
  frontend/src/theme/palette.ts
  frontend/src/theme/variables.css
Labels: 🔍 Ready for Review, ✅ Approved, size/XL

#45 Feat/create collective
  frontend/src/App.tsx
  frontend/src/components/Mint/MintTopBar.tsx
  frontend/src/hooks/Groups/useGetMyGroups.ts
  frontend/src/pages/Mint/CollectiveInvites.tsx
  frontend/src/pages/Mint/CreateCollective.tsx
  frontend/src/pages/Mint/Group.tsx
  frontend/src/pages/Mint/ManageCollective.tsx
  frontend/src/pages/Mint/Mint.tsx
  frontend/src/pages/Mint/MintGroupsContent.tsx
  frontend/src/pages/Mint/NoGroups.tsx
  frontend/src/theme/main.css
  frontend/src/utils/routeNames.ts
Labels: 🔍 Ready for Review, size/XL

#46 Feat/create collective
  backend/src/services/groups.ts
  backend/src/utils/zora.ts
  frontend/src/components/Mint/CollectiveList.tsx
  frontend/src/hooks/Groups/useGetMyGroups.ts
  frontend/src/pages/Mint/CreateCollective.tsx
  frontend/src/pages/Mint/CreatePool.tsx
  frontend/src/pages/Mint/Mint.tsx
  frontend/src/pages/Mint/MintGroupsContent.tsx
  frontend/src/services/ApiService.ts
  frontend/src/theme/main.css
  frontend/src/theme/variables.css
  frontend/src/types/chat.ts
  frontend/src/utils/routeNames.ts
Labels: ✅ Approved, size/XL

#47 feat: changes for discover swiper updated icons and styles
  frontend/public/assets/icons/add.svg
  frontend/public/assets/icons/message-tile.svg
  frontend/public/assets/icons/mint-tile.svg
  frontend/public/assets/icons/people-tile.svg
  frontend/src/App.tsx
  frontend/src/components/Images/HorizontalSwipe.tsx
  frontend/src/components/Images/SwipeCard.tsx
  frontend/src/components/PageSearchBar.tsx
  frontend/src/components/TabsMenu.tsx
  frontend/src/pages/Discover/About.tsx
  frontend/src/pages/Discover/Discover.tsx
  frontend/src/pages/Discover/DiscoverTopBar.tsx
  frontend/src/pages/Discover/New.tsx
  frontend/src/pages/Mint/CollectiveInvites.tsx
  frontend/src/pages/Mint/ManageCollective.tsx
  frontend/src/pages/Mint/MintGroupsContent.tsx
  frontend/src/theme/main.css
  frontend/src/utils/routeNames.ts
Labels: 🔍 Ready for Review, size/L

#51 Feat/add pools
  backend/src/controllers/v1/challenges.ts
  backend/src/controllers/v1/groups.ts
  backend/src/middlewares/authentication.ts
  backend/src/services/groups.ts
  backend/src/utils/zora.ts
  frontend/src/components/Challenges/ChallengeItemCard.tsx
  frontend/src/components/Images/HorizontalSwipe.tsx
  frontend/src/components/Images/SwipeCard.tsx
  frontend/src/components/Mint/CollectiveList.tsx
  frontend/src/pages/Mint/CreateCollective.tsx
  frontend/src/pages/Mint/MintGroupsContent.tsx
  frontend/src/pages/Mint/NoGroups.tsx
  frontend/src/pages/Mint/SelectPoolModal.tsx
  frontend/src/services/ApiService.ts
Labels: ✅ Approved, size/L

#54 Feat/invites refactor
  backend/src/controllers/v1/groups.ts
  backend/src/controllers/v1/invite.ts
  backend/src/routes/v1/invite.ts
  backend/src/services/groups.ts
  backend/src/services/invites.ts
  backend/src/utils/index.ts
  backend/src/utils/invite-codes.ts
  frontend/src/App.tsx
  frontend/src/components/Mint/MintTopBar.tsx
  frontend/src/components/SideBarMenu.tsx
  frontend/src/components/TabsMenu.tsx
  frontend/src/pages/Discover/Discover.tsx
  frontend/src/pages/Home.tsx
  frontend/src/pages/Invite.tsx
  frontend/src/pages/Mint/CollectiveInvites.tsx
  frontend/src/theme/main.css
  frontend/src/utils/routeNames.ts
Labels: ✅ Approved, size/L

#56 Fix/auth issues
  backend/src/data/migrations/20231123103412_users_address_unique.ts
  frontend/src/components/ConnectButton.tsx
  frontend/src/hooks/Groups/useGetMyGroups.ts
  frontend/src/hooks/Groups/useGetNumberOfMembersInGroup.tsx
  frontend/src/hooks/useCheckAuth.ts
  frontend/src/hooks/useSignInWallet.ts
  frontend/src/pages/Login.tsx
  frontend/src/services/ApiService.ts
  frontend/src/services/NetworkService.js
  frontend/src/utils/auth.ts
  frontend/src/utils/checkAuth.ts
  frontend/src/utils/index.ts
Labels: ✅ Approved, size/L

#58 Fix/invite codes
  backend/src/config/database.ts
  backend/src/data/migrations/20231123103412_users_address_unique.ts
  backend/src/data/migrations/20231123112800_invites_group_optional.ts
  backend/src/data/seeds/dev/1_user-groups-challenges.ts
  backend/src/data/seeds/dev/2_invites.ts
  backend/src/services/auth.ts
  backend/src/services/groups.ts
Labels: ✅ Approved, size/L

#61 Feat/invite screen
  backend/src/controllers/v1/invite.ts
  backend/src/data/migrations/20231123190040_invites_user_id.ts
  backend/src/routes/v1/invite.ts
  backend/src/services/groups.ts
  backend/src/services/invites.ts
  frontend/public/assets/icons/congrats.svg
  frontend/src/App.tsx
  frontend/src/components/SideBarMenu.tsx
  frontend/src/components/TabsMenu.tsx
  frontend/src/pages/Home.tsx
  frontend/src/pages/Invite.tsx
  frontend/src/pages/Join.tsx
  frontend/src/services/Invites.ts
  frontend/src/theme/main.css
  frontend/src/utils/adddress.ts
Labels: ✅ Approved, size/XL

#63 Feat/chat styles
  backend/src/controllers/v1/invite.ts
  backend/src/data/seeds/dev/1_user-groups-challenges.ts
  backend/src/data/seeds/dev/2_invites.ts
  frontend/package-lock.json
  frontend/src/App.tsx
  frontend/src/components/Chat.tsx
  frontend/src/components/GenerateInvite.tsx
  frontend/src/components/Mint/FullListOfCollectives.tsx
  frontend/src/components/Mint/MembersTable.tsx
  frontend/src/components/TopBars/CollectiveTopBar.tsx
  frontend/src/hooks/useToast.tsx
  frontend/src/pages/Mint/CollectiveDetail/CollectiveChat.tsx
  frontend/src/pages/Mint/CollectiveDetail/CollectiveDetail.tsx
  frontend/src/pages/Mint/CollectiveDetail/CollectiveInfo.tsx
  frontend/src/pages/Mint/CollectiveDetail/CollectiveMint.tsx
  frontend/src/pages/Mint/CreatePool.tsx
  frontend/src/services/ApiService.ts
  frontend/src/theme/main.css
  frontend/src/theme/palette.ts
  frontend/src/utils/adddress.ts
  frontend/src/utils/routeNames.ts
Labels: 🔍 Ready for Review, size/XL

#64 debug CLAIM endpoint, added authentication, right URL, added DB row u…
  backend/src/controllers/v1/invite.ts
  backend/src/data/migrations/20231103041211_create_table_invites.ts
  backend/src/routes/v1/invite.ts
  frontend/src/components/GenerateInvite.tsx
  frontend/src/pages/Invite.tsx
  frontend/src/services/ApiService.ts
  frontend/src/services/Invites.ts
  frontend/src/theme/main.css
Labels: 🔍 Ready for Review, ✅ Approved, size/M

#65 debug invite flow, delete old logic
  backend/src/controllers/v1/groups.ts
  backend/src/controllers/v1/invite.ts
  backend/src/data/migrations/20231103041211_create_table_invites.ts
  backend/src/data/seeds/dev/2_invites.ts
  backend/src/services/groups.ts
  backend/src/services/invites.ts
  backend/src/utils/invite-codes.ts
  frontend/src/components/GenerateInvite.tsx
  frontend/src/hooks/useSignInWallet.ts
  frontend/src/pages/Invite.tsx
Labels: 🔍 Ready for Review, size/L

#66 fix build errors
  frontend/src/components/Mint/PoolsGrid.tsx
  frontend/src/pages/Mint/CollectiveDetail/CollectiveMint.tsx
  frontend/src/types/challenges.ts
Labels: 🔍 Ready for Review, size/S

#68 Feat/group joins
  backend/src/controllers/v1/groups.ts
  backend/src/models/group.ts
  backend/src/services/groups.ts
  frontend/public/assets/icons/mint-tile-white.svg
  frontend/public/assets/mint-tile.svg
  frontend/src/components/Mint/FullListOfCollectives.tsx
  frontend/src/hooks/Groups/useGetMyGroups.ts
  frontend/src/theme/main.css
Labels: ✅ Approved, size/L
