Repository liquality/my-collectives-pwa, pull requests merged in 2023-10, with the labels that each got.

#2 Feat/firebase chat
  .env
  .gitignore
  package-lock.json
  package.json
  src/components/Auth.tsx
  src/components/Chat.tsx
  src/components/ProtectedRoute.tsx
  src/firebase.config.js
  src/pages/Login.tsx
  src/pages/Room.tsx
  src/theme/chat-box.css
  tsconfig.json
Labels: 🔍 Ready for Review, size/L

#3 feat: first version of connect and disconnect flow
  .env.example
  src/components/ConnectModal.tsx
  src/components/Header.tsx
  src/types/wallet.ts
  src/utils/WalletProvider.tsx
Labels: 🔍 Ready for Review, size/L

#4 feat: added pwa asset generator
  .env
  .gitignore
  README.md
  index.html
  package-lock.json
  package.json
  public/apple-touch-icon-180x180.png
  public/favicon.ico
  public/icon-192x192.png
  public/icon-256x256.png
  public/icon-384x384.png
  public/icon-512x512.png
  public/logo.svg
  public/manifest.json
  public/maskable-icon-512x512.png
  public/pwa-192x192.png
  public/pwa-512x512.png
  public/pwa-64x64.png
  pwa-assets.config.ts
  src/components/Header.tsx
  vite.config.ts
Labels: 🔍 Ready for Review, size/L

#7 Feat/implement embedded wallet flow
  .gitignore
  .vite/deps_temp_0f9eb405/package.json
  frontend/package-lock.json
  frontend/public/apple-touch-icon-180x180.png
  frontend/public/favicon.ico
  frontend/public/logo.svg
  frontend/public/maskable-icon-512x512.png
  frontend/public/pwa-192x192.png
  frontend/public/pwa-512x512.png
  frontend/public/pwa-64x64.png
  frontend/src/App.tsx
  frontend/src/components/ConnectButton.tsx
  frontend/src/components/ConnectModal.tsx
  frontend/src/components/ExploreContainer.css
  frontend/src/components/ExploreContainer.tsx
  frontend/src/components/Header.tsx
  frontend/src/pages/Settings.tsx
  frontend/src/theme/main.css
  frontend/src/theme/variables.css
  frontend/src/types/wallet.ts
  frontend/src/utils/WalletProvider.tsx
  frontend/src/utils/address.ts
  frontend/src/utils/globalState.ts
  frontend/src/utils/index.ts
Labels: 🔍 Ready for Review, size/XL

#8 Feat/add backend
  .gitignore
  backend/index.js
  backend/package-lock.json
  backend/package.json
  backend/sql/create.sql
  backend/v1/classes/Group.js
  backend/v1/classes/Invite.js
  backend/v1/classes/Message.js
  backend/v1/classes/User.js
  backend/v1/endpoints.js
  backend/v1/handlers/groupHandler.js
  backend/v1/handlers/inviteHandler.js
  backend/v1/handlers/messageHandler.js
  backend/v1/services/WebsocketService.js
  frontend/src/App.tsx
  frontend/src/components/Auth.tsx
  frontend/src/components/Chat.tsx
  frontend/src/components/GenerateInvite.tsx
  frontend/src/hooks/useChatHistory.ts
  frontend/src/hooks/useGetGroups.ts
  frontend/src/hooks/useValidateInvite.ts
  frontend/src/pages/Invite.tsx
  frontend/src/pages/Room.tsx
  frontend/src/services/NetworkService.js
  frontend/src/services/UserService.ts
  frontend/src/types/chat.ts
Labels: 🔍 Ready for Review, size/XL

#12 Feat/backend ts
  backend/package.json
  backend/src/index.ts
  backend/src/v1/classes/Group.ts
  backend/src/v1/classes/Message.ts
  backend/src/v1/handlers/groupHandler.ts
  backend/src/v1/handlers/messageHandler.ts
  backend/src/v1/helper.js
  backend/src/v1/helper.ts
  backend/src/v1/middleware.ts
  backend/src/v1/services/WebsocketService.js
  backend/yarn.lock
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Chat.tsx
  frontend/src/hooks/useChatHistory.ts
  frontend/src/hooks/useSocket.ts
  frontend/src/pages/Room.tsx
  frontend/src/services/NetworkService.js
  frontend/src/services/SocketService.ts
  frontend/src/services/Websocket/EventBus.ts
  frontend/src/services/Websocket/MessageHandler.ts
  frontend/src/services/Websocket/WebsocketService.js
Labels: ✅ Approved, size/L

#11 feat: removed third web sdk / use wagmi with wallet connect and metamask
  frontend/.env.example
  frontend/README.md
  frontend/bun.lockb
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/ConnectButton.tsx
  frontend/src/utils/WalletProvider.tsx
  frontend/src/utils/index.ts
Labels: ✅ Approved, size/L

#14 Feat/auth
  backend/.nvmrc
  backend/README.md
  backend/config/config.json
  backend/models/index.js
  backend/src/MySQL.ts
  backend/src/sql/create.sql
  backend/src/v1/classes/Auth.ts
  backend/src/v1/handlers/authHandler.ts
  backend/src/v1/middleware.ts
  backend/tsconfig.json
  backend/yarn.lock
  frontend/bun.lockb
  frontend/bunfig.toml.example
  frontend/package-lock.json
Labels: ✅ Approved, size/L

#17 Feat/pools
  backend/package-lock.json
  backend/package.json
  backend/src/index.ts
  backend/src/v1/classes/Member.ts
  backend/src/v1/dummydata.ts
  backend/src/v1/endpoints.ts
  backend/src/v1/handlers/moralisHandler.ts
  backend/src/v1/helper.ts
  backend/yarn.lock
  frontend/.env.example
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/Chat.tsx
  frontend/src/components/GenerateInvite.tsx
  frontend/src/components/Groups/CreateGroup.tsx
  frontend/src/components/Groups/useGetGroupById.tsx
  frontend/src/components/Pools/PoolLeaderboard.tsx
  frontend/src/components/Pools/PoolRows.tsx
  frontend/src/hooks/Groups/useGetMyGroups.ts
  frontend/src/hooks/Groups/useGetNumberOfMembersInGroup.tsx
  frontend/src/hooks/Pools/useGetLeaderboard.tsx
  frontend/src/hooks/Pools/useGetPoolsMetadata.tsx
  frontend/src/hooks/useChatHistory.ts
  frontend/src/hooks/useValidateInvite.ts
  frontend/src/pages/Groups.tsx
  frontend/src/pages/Home.tsx
  frontend/src/pages/Invite.tsx
  frontend/src/pages/Login.tsx
  frontend/src/pages/Messages.tsx
  frontend/src/pages/Pool.tsx
  frontend/src/pages/Pools.tsx
  frontend/src/pages/Settings.tsx
  frontend/src/poolsdummydata.ts
  frontend/src/services/ApiService.ts
  frontend/src/services/MoralisService.ts
  frontend/src/theme/main.css
  frontend/src/utils/adddress.ts
Labels: 🔍 Ready for Review, size/XXL

#18 Feat/authflow menu UI
  backend/src/v1/classes/Auth.ts
  backend/src/v1/classes/Member.ts
  backend/src/v1/endpoints.ts
  backend/src/v1/handlers/authHandler.ts
  frontend/src/App.tsx
  frontend/src/components/ConnectButton.tsx
  frontend/src/components/Menu.tsx
  frontend/src/components/SideBarMenu.tsx
  frontend/src/components/TabsMenu.tsx
  frontend/src/hooks/useCheckAuth.ts
  frontend/src/hooks/useSignInWallet.ts
  frontend/src/hooks/userWindowsDimensions.ts
  frontend/src/pages/Discover.tsx
  frontend/src/pages/Messages.tsx
  frontend/src/pages/Rewards.tsx
  frontend/src/services/ApiService.ts
  frontend/src/utils/checkAuth.ts
  frontend/yarn.lock
Labels: 🔍 Ready for Review, size/XXL

#19 Feat/create pools
  backend/package-lock.json
  backend/package.json
  backend/src/sql/create.sql
  backend/src/v1/classes/Pool.ts
  backend/src/v1/endpoints.ts
  backend/src/v1/handlers/poolHandler.ts
  backend/src/v1/helper.ts
  backend/yarn.lock
  frontend/package-lock.json
  frontend/src/components/Pools/PoolRows.tsx
  frontend/src/components/ProtectedRoute.tsx
  frontend/src/hooks/Pools/useGetPoolsMetadata.tsx
  frontend/src/pages/Discover.tsx
  frontend/src/pages/Pool.tsx
  frontend/src/services/ApiService.ts
  frontend/src/theme/main.css
  frontend/src/utils/adddress.ts
  frontend/yarn.lock
Labels: ✅ Approved, size/XXL

#20 feat: updated ui for groups messages and discover list of pools
  frontend/.env.example
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/Chat.tsx
  frontend/src/components/ConnectButton.tsx
  frontend/src/components/Groups/CreateGroup.tsx
  frontend/src/components/Groups/GroupRows.tsx
  frontend/src/components/Header.tsx
  frontend/src/components/Pools/PoolItemCard.tsx
  frontend/src/components/Pools/PoolLeaderboard.tsx
  frontend/src/components/Pools/PoolRows.tsx
  frontend/src/components/SideBarMenu.tsx
  frontend/src/components/TabsMenu.tsx
  frontend/src/hooks/Groups/useGetGroupById.ts
  frontend/src/hooks/Groups/useGetMyGroups.ts
  frontend/src/hooks/Pools/useGetLeaderboard.tsx
  frontend/src/pages/Discover.tsx
  frontend/src/pages/Groups.tsx
  frontend/src/pages/Login.tsx
  frontend/src/pages/Messages.tsx
  frontend/src/pages/Mint/CreateGroupModal.tsx
  frontend/src/pages/Mint/GroupRows.tsx
  frontend/src/pages/Mint/Mint.tsx
  frontend/src/pages/Pool.tsx
  frontend/src/pages/Pools.tsx
  frontend/src/pages/Rewards.tsx
  frontend/src/pages/Settings.tsx
  frontend/src/services/NetworkService.js
  frontend/src/theme/main.css
  frontend/src/theme/variables.css
  frontend/vite.config.ts
  frontend/yarn.lock
Labels: ✅ Approved, size/XXL

#21 Feat/sound leaderboard
  backend/package-lock.json
  backend/package.json
  backend/src/v1/constants.ts
  backend/src/v1/endpoints.ts
  backend/src/v1/handlers/moralisHandler.ts
  backend/src/v1/helper.ts
  frontend/package-lock.json
  frontend/yarn.lock
Labels: 🔍 Ready for Review, size/XXL
