Repository liquality/my-collectives-pwa, pull requests merged in 2023-12, with the labels that each got.

#69 Feat/rewards page
  backend/package-lock.json
  frontend/package-lock.json
  frontend/src/App.tsx
  frontend/src/components/Chat.tsx
  frontend/src/components/GenerateInvite.tsx
  frontend/src/components/TopBars/RewardsTopBar.tsx
  frontend/src/pages/Mint/CollectiveDetail/CollectiveInfo.tsx
  frontend/src/pages/Mint/CollectiveInvites.tsx
  frontend/src/pages/Mint/Mint.tsx
  frontend/src/pages/Mint/MintCollectiveContent.tsx
  frontend/src/pages/Mint/MyMints.tsx
  frontend/src/pages/Rewards.tsx
  frontend/src/pages/Rewards/Airdrops.tsx
  frontend/src/pages/Rewards/Rewards.tsx
  frontend/src/pages/Rewards/Summary.tsx
  frontend/src/theme/main.css
  frontend/src/types/chat.ts
  frontend/src/utils/routeNames.ts
Labels: 🔍 Ready for Review, size/L

#70 Feat/challenges screens
  backend/package-lock.json
  frontend/public/assets/icons/arrow-outside.svg
  frontend/public/assets/icons/modal-handle.svg
  frontend/src/App.tsx
  frontend/src/components/Challenges/ChallengeItemCard.tsx
  frontend/src/components/Challenges/ChallengeItemInfoSheetModal.tsx
  frontend/src/components/Challenges/ChallengeItemModal.tsx
  frontend/src/components/Challenges/InfoSheetModalDetails.tsx
  frontend/src/components/Challenges/InfoSheetModalMintActivity.tsx
  frontend/src/components/Challenges/InfoSheetModalOverview.tsx
  frontend/src/components/Images/ImageLoader.tsx
  frontend/src/components/Images/SwipeCard.tsx
  frontend/src/hooks/Challenges/useGetChallenges.tsx
  frontend/src/pages/Discover/New.tsx
  frontend/src/pages/Mint/Challenges.tsx
  frontend/src/services/NetworkService.js
  frontend/src/theme/main.css
Labels: 🔍 Ready for Review, size/XL

#72 Feat/rewards table
  backend/src/data/migrations/20231101142556_create_table_users.ts
  backend/src/data/migrations/20231103005059_create_table_groups.ts
  backend/src/data/migrations/20231103040636_create_table_pools.ts
  backend/src/data/migrations/20231206122920_user_rewards.ts
  frontend/package-lock.json
  frontend/src/pages/Mint/CreateCollective.tsx
  frontend/src/pages/Mint/CreatePool.tsx
Labels: ✅ Approved, size/L

#74 Feat/standardize challenges
  backend/package-lock.json
  backend/package.json
  backend/src/config/database.ts
  backend/src/controllers/v1/challenges.ts
  backend/src/controllers/v1/invite.ts
  backend/src/controllers/v1/nft.ts
  backend/src/data/migrations/20231103005205_create_table_challenges.ts
  backend/src/data/migrations/20231123103412_users_address_unique.ts
  backend/src/data/migrations/20231206122920_user_rewards.ts
  backend/src/data/seeds/dev/1_user-groups-challenges.ts
  backend/src/routes/v1/nft.ts
  backend/src/services/auth.ts
  backend/src/services/challenges.ts
  backend/src/utils/date.ts
  backend/src/utils/index.ts
  backend/src/utils/reservoir-metadata.ts
  backend/src/utils/zora-graphql.ts
  frontend/src/components/Challenges/PoolLeaderboard.tsx
  frontend/src/components/Images/SwipeCard.tsx
  frontend/src/components/Mint/PoolItemCard.tsx
  frontend/src/components/Mint/PoolsGrid.tsx
  frontend/src/components/TopBars/CollectiveTopBar.tsx
  frontend/src/hooks/Collective/useGetPoolsByGroupId.tsx
  frontend/src/hooks/Groups/useGetMyGroups.ts
  frontend/src/pages/Discover/CreateChallengeModal.tsx
  frontend/src/pages/Discover/New.tsx
  frontend/src/pages/Rewards/Summary.tsx
  frontend/src/types/challenges.ts
  frontend/src/utils/adddress.ts
Labels: ✅ Approved, size/L

#75 Feat/challenge detail info
  backend/src/controllers/v1/nft.ts
  backend/src/data/migrations/20231103005205_create_table_challenges.ts
  backend/src/routes/v1/nft.ts
  backend/src/services/challenges.ts
  backend/src/utils/index.ts
  backend/src/utils/reservoir-api/floorprice.ts
  backend/src/utils/reservoir-api/leaderboard.ts
  backend/src/utils/reservoir-api/token-metadata.ts
  frontend/src/components/ChallengeSwipeModal/ChallengeItemInfoSheetModal.tsx
  frontend/src/components/ChallengeSwipeModal/InfoSheetModalMintActivity.tsx
  frontend/src/components/Challenges/PoolLeaderboard.tsx
  frontend/src/hooks/Challenges/useGetLeaderboard.tsx
  frontend/src/hooks/Challenges/useGetMintActivity.tsx
  frontend/src/pages/Discover/New.tsx
  frontend/src/pages/Mint/Challenge.tsx
  frontend/src/services/ApiService.ts
  frontend/src/types/challenges.ts
Labels: ✅ Approved, size/L

#77 Feat/pricefloordata
  backend/src/controllers/v1/groups.ts
  backend/src/utils/reservoir-api/floorprice.ts
  backend/src/utils/reservoir-api/token-metadata.ts
  frontend/src/components/ChallengesModal/ChallengeItemInfoSheetModal.tsx
  frontend/src/components/ChallengesModal/ChallengeItemModal.tsx
  frontend/src/components/Images/SwipeCard.tsx
  frontend/src/hooks/useSignInWallet.ts
  frontend/src/pages/Discover/CreateChallengeModal.tsx
  frontend/src/pages/Mint/CreateCollective.tsx
  frontend/src/pages/Mint/SelectPoolModal.tsx
  frontend/src/pages/Rewards/ManageCollective.tsx
  frontend/src/utils/adddress.ts
Labels: ✅ Approved, size/M

#79 Feat/creator address
  backend/src/controllers/v1/challenges.ts
  backend/src/data/migrations/20231103005059_create_table_groups.ts
  backend/src/data/migrations/20231103005205_create_table_challenges.ts
  backend/src/data/seeds/dev/1_user-groups-challenges.ts
  backend/src/models/challenges.ts
  backend/src/routes/v1/challenges.ts
  backend/src/services/challenges.ts
  backend/src/services/pools.ts
  backend/src/utils/reservoir-api/token-metadata.ts
  frontend/src/components/Chat.tsx
  frontend/src/hooks/Collective/useGetPoolsByGroupId.tsx
  frontend/src/pages/Discover/CreateChallengeModal.tsx
  frontend/src/pages/Discover/New.tsx
  frontend/src/types/challenges.ts
  frontend/src/types/general-types.ts
Labels: 🔍 Ready for Review, ✅ Approved, size/L

#80 Feat/update challenges data
  backend/src/controllers/v1/challenges.ts
  backend/src/models/challenges.ts
  backend/src/routes/v1/challenges.ts
  backend/src/services/challenges.ts
  backend/src/utils/reservoir-api/token-metadata.ts
  frontend/src/components/GenerateInvite.tsx
  frontend/src/components/Images/HorizontalSwipe.tsx
  frontend/src/hooks/Challenges/useGetChallenges.tsx
  frontend/src/hooks/useToast.tsx
  frontend/src/pages/Discover/CreateChallengeModal.tsx
  frontend/src/pages/Discover/New.tsx
  frontend/src/pages/Mint/CreateCollective.tsx
Labels: ✅ Approved, size/L

#81 Feat/mint pages
  frontend/public/assets/icons/social_discord.svg
  frontend/public/assets/icons/social_sound.svg
  frontend/public/assets/icons/social_telegram.svg
  frontend/public/assets/icons/social_twitter.svg
  frontend/src/components/ChallengesModal/ChallengeItemInfoSheetModal.tsx
  frontend/src/components/ChallengesModal/ChallengeItemMintModal.tsx
  frontend/src/components/ChallengesModal/ChallengeItemModal.tsx
  frontend/src/components/GenerateInvite.tsx
  frontend/src/components/Mint/MembersTable.tsx
  frontend/src/components/Mint/MintItemContent.tsx
  frontend/src/components/Mint/MintItemResult.tsx
  frontend/src/components/Mint/MintItemScreen.tsx
  frontend/src/pages/Discover/New.tsx
  frontend/src/pages/Mint/CreateCollective.tsx
  frontend/src/theme/main.css
  frontend/src/types/challenges.ts
  frontend/src/types/mint.ts
Labels: 🔍 Ready for Review, ✅ Approved, size/XL

#82 Feat/header changes
  frontend/src/components/Header.tsx
  frontend/src/pages/Mint/MyMints.tsx
  frontend/src/theme/main.css
Labels: ✅ Approved, size/L

#83 Feat/mint functionality
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Mint/MintItemContent.tsx
  frontend/src/components/MintZoraLogic.tsx
  frontend/src/pages/Rewards/Airdrops.tsx
Labels: 🔍 Ready for Review, size/L

#85 Feat/ens name
  backend/src/controllers/v1/challenges.ts
  backend/src/services/challenges.ts
  frontend/src/components/ConnectButton.tsx
  frontend/src/components/Images/HorizontalSwipe.tsx
  frontend/src/components/Images/SwipeCard.tsx
  frontend/src/components/Mint/MintItemContent.tsx
  frontend/src/components/Mint/MintItemResult.tsx
  frontend/src/components/Mint/PoolItemCard.tsx
  frontend/src/hooks/useDisplayEns.tsx
  frontend/src/pages/Discover/New.tsx
  frontend/src/pages/Mint/CreateCollective.tsx
  frontend/src/pages/Mint/MintCollectiveContent.tsx
  frontend/src/pages/Mint/MyMints.tsx
  frontend/src/pages/Rewards/ManageCollective.tsx
  frontend/src/utils/adddress.ts
  frontend/src/utils/ensName.ts
Labels: 🔍 Ready for Review, ✅ Approved, size/L

#84 feat: added / reused challenge modal for challenges pages, fixed rout…
  frontend/src/App.tsx
  frontend/src/components/Challenges/ChallengeItemCard.tsx
  frontend/src/components/Challenges/ChallengeRows.tsx
  frontend/src/components/ChallengesModal/ChallengeImageCard.tsx
  frontend/src/components/ChallengesModal/ChallengeItemInfoSheetModal.tsx
  frontend/src/components/ChallengesModal/ChallengeItemModal.tsx
  frontend/src/components/Mint/FullListOfCollectives.tsx
  frontend/src/components/Mint/MintItemContent.tsx
  frontend/src/components/TopBars/CollectiveTopBar.tsx
  frontend/src/hooks/Collective/useGetChallengesByGroupId.tsx
  frontend/src/hooks/useIsActiveRoute.ts
  frontend/src/pages/Discover/New.tsx
  frontend/src/pages/Mint/Challenge.tsx
  frontend/src/pages/Mint/Challenges.tsx
  frontend/src/pages/Mint/CollectiveDetail/CollectiveDetail.tsx
  frontend/src/pages/Mint/CollectiveDetail/CollectiveMint.tsx
  frontend/src/pages/Mint/Group.tsx
  frontend/src/pages/Mint/Mint.tsx
  frontend/src/pages/Mint/MintCollectiveContent.tsx
  frontend/src/pages/Mint/MyMints.tsx
  frontend/src/pages/Rewards/ManageCollective.tsx
  frontend/src/services/ApiService.ts
  frontend/src/types/challenges.ts
  frontend/src/utils/adddress.ts
  frontend/src/utils/routeNames.ts
Labels: 🔍 Ready for Review, size/XL

#86 Feat/create collective sdk
  backend/src/controllers/v1/groups.ts
  backend/src/data/migrations/20231103005059_create_table_groups.ts
  backend/src/services/groups.ts
  backend/src/services/invites.ts
  backend/src/utils/reservoir-api/token-metadata.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/GenerateInvite.tsx
  frontend/src/components/MintZoraLogic.tsx
  frontend/src/pages/Invite.tsx
  frontend/src/pages/Mint/CreateCollective.tsx
  frontend/src/services/ApiService.ts
  frontend/src/services/ContractService.ts
  frontend/src/types/general-types.ts
  frontend/src/utils/salt.ts
Labels: 🔍 Ready for Review, size/L

#87 feat: added handle nft mint page
  backend/src/routes/v1/challenges.ts
  frontend/src/App.tsx
  frontend/src/hooks/useIsActiveRoute.ts
  frontend/src/pages/Mint/Mint.tsx
  frontend/src/pages/Mint/NFTPage.tsx
  frontend/src/services/ApiService.ts
  frontend/src/utils/routeNames.ts
Labels: 🔍 Ready for Review, size/M

#88 Feat/collective screens
  backend/src/services/groups.ts
  frontend/src/components/Chat.tsx
  frontend/src/components/Mint/MembersTable.tsx
  frontend/src/hooks/Groups/useGetGroupById.ts
  frontend/src/pages/Mint/CollectiveDetail/CollectiveChat.tsx
  frontend/src/pages/Mint/CollectiveDetail/CollectiveInfo.tsx
  frontend/src/pages/Mint/Messages.tsx
  frontend/src/services/ApiService.ts
  frontend/src/theme/main.css
Labels: ✅ Approved, size/L

#89 Feat/remaining UI screens
  frontend/src/components/Challenges/ChallengeItemCard.tsx
  frontend/src/components/ChallengesModal/ChallengeItemInfoSheetModal.tsx
  frontend/src/components/ChallengesModal/InfoSheetModalDetails.tsx
  frontend/src/components/ChallengesModal/InfoSheetModalMintActivity.tsx
  frontend/src/components/ChallengesModal/InfoSheetModalOverview.tsx
Labels: 🔍 Ready for Review, ✅ Approved, size/L

#91 Feat/goerli testing
  backend/src/utils/reservoir-api/token-metadata.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/ChallengesModal/ChallengeItemInfoSheetModal.tsx
  frontend/src/components/ChallengesModal/InfoSheetModalOverview.tsx
  frontend/src/components/Mint/MintItemContent.tsx
  frontend/src/components/MintZoraLogic.tsx
  frontend/src/hooks/useGetZoraSDKParams.tsx
  frontend/src/pages/Discover/CreateChallengeModal.tsx
  frontend/src/pages/Invite.tsx
  frontend/src/services/ContractService.ts
  frontend/src/types/challenges.ts
  frontend/src/utils/adddress.ts
  package-lock.json
  package.json
Labels: ✅ Approved, size/L

#92 Feat/rewards endpoint
  backend/src/controllers/v1/index.ts
  backend/src/controllers/v1/pools.ts
  backend/src/controllers/v1/user.ts
  backend/src/routes/v1/index.ts
  backend/src/routes/v1/user.ts
  backend/src/services/user.ts
  frontend/src/hooks/userGetRewardsSummary.ts
  frontend/src/pages/Rewards/Summary.tsx
  frontend/src/services/ApiService.ts
Labels: 🔍 Ready for Review, ✅ Approved, size/L

#93 Feat/goerli testing
  backend/src/services/groups.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Mint/MintItemContent.tsx
  frontend/src/hooks/useGetZoraSDKParams.tsx
  frontend/src/services/ContractService.ts
Labels: 🔍 Ready for Review, size/L

#94 feat: added list of groups inside mint content
  backend/src/controllers/v1/groups.ts
  backend/src/routes/v1/groups.ts
  backend/src/services/groups.ts
  frontend/src/components/Mint/MintItemContent.tsx
  frontend/src/hooks/Groups/useGetGroupsByChallenge.ts
  frontend/src/services/ApiService.ts
Labels: 🔍 Ready for Review, size/L

#95 Feat/goerli testing
  backend/src/services/challenges.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Mint/MintItemContent.tsx
  frontend/src/components/Mint/MintItemScreen.tsx
  frontend/src/hooks/Groups/useGetGroupsByChallenge.ts
  frontend/src/pages/Mint/CreateCollective.tsx
  frontend/src/services/ContractService.ts
  frontend/src/types/general-types.ts
  frontend/src/utils/salt.ts
Labels: 🔍 Ready for Review, size/M

#96 feat: create pool when manage collective
  backend/src/services/groups.ts
  frontend/src/pages/Rewards/ManageCollective.tsx
  frontend/src/services/ContractService.ts
Labels: 🔍 Ready for Review, size/L

#97 Feat/mint debug
  backend/src/data/seeds/dev/1_user-groups-challenges.ts
  backend/src/services/challenges.ts
  backend/src/utils/reservoir-api/floorprice.ts
  backend/src/utils/reservoir-api/token-metadata.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/ChallengesModal/ChallengeItemInfoSheetModal.tsx
  frontend/src/components/Mint/MintItemContent.tsx
  frontend/src/hooks/useGetZoraSDKParams.tsx
  frontend/src/pages/Discover/CreateChallengeModal.tsx
  frontend/src/pages/Discover/New.tsx
  frontend/src/pages/Mint/CreateCollective.tsx
  frontend/src/pages/Mint/MyMints.tsx
  frontend/src/services/ContractService.ts
  frontend/src/types/challenges.ts
  frontend/src/utils/fee.ts
Labels: 🔍 Ready for Review, size/XL
