Repository liquality/my-collectives-pwa, pull requests merged in 2024-01, with the labels that each got.

#99 Feat/group rewards
  backend/package-lock.json
  backend/package.json
  backend/src/controllers/v1/pools.ts
  backend/src/data/seeds/dev/1_user-groups-challenges.ts
  backend/src/services/challenges.ts
  backend/src/services/groups.ts
  backend/src/services/pools.ts
  backend/src/utils/constants.ts
  backend/src/utils/events-query/top-contributor-zora.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Mint/MintItemContent.tsx
  frontend/src/services/ContractService.ts
Labels: 🔍 Ready for Review, size/XXL

#100 Feat/group admin flow
  backend/src/controllers/v1/groups.ts
  backend/src/data/migrations/20231101142556_create_table_users.ts
  backend/src/models/group.ts
  backend/src/routes/v1/groups.ts
  backend/src/services/auth.ts
  backend/src/services/groups.ts
  frontend/.env.example
  frontend/package-lock.json
  frontend/src/components/Mint/FullListOfCollectives.tsx
  frontend/src/components/Mint/MembersTable.tsx
  frontend/src/pages/Discover/CreateChallengeModal.tsx
  frontend/src/pages/Discover/New.tsx
  frontend/src/pages/Mint/CollectiveDetail/CollectiveInfo.tsx
  frontend/src/pages/Rewards/Summary.tsx
  frontend/src/services/ApiService.ts
  frontend/src/services/ContractService.ts
  frontend/src/types/general-types.ts
Labels: ✅ Approved, size/L

#102 add more data to the CollectiveInfo page from db
  backend/src/controllers/v1/groups.ts
  backend/src/models/group.ts
  backend/src/services/groups.ts
  frontend/src/pages/Mint/CollectiveDetail/CollectiveInfo.tsx
Labels: 🔍 Ready for Review, size/M

#104 Bugfix/qa round1
  backend/src/controllers/v1/groups.ts
  backend/src/services/challenges.ts
  frontend/src/App.tsx
  frontend/src/components/PageSearchBar.tsx
  frontend/src/pages/Discover/New.tsx
  frontend/src/pages/Mint/CollectiveDetail/CollectiveInfo.tsx
  frontend/src/pages/Mint/CreateCollective.tsx
  frontend/src/pages/Mint/SelectPoolModal.tsx
  frontend/src/pages/Rewards/ManageCollective.tsx
  frontend/src/pages/Rewards/Rewards.tsx
  frontend/src/services/ContractService.ts
  frontend/src/theme/main.css
Labels: 🔍 Ready for Review, size/L

#106 Feat/withdraw
  backend/src/controllers/v1/pools.ts
  backend/src/services/pools.ts
  backend/src/utils/reservoir-api/token-metadata.ts
  frontend/src/pages/Mint/CollectiveDetail/CollectiveInfo.tsx
  frontend/src/pages/Mint/MyMints.tsx
  frontend/src/services/ContractService.ts
Labels: ✅ Approved, size/L

#103 Feat/get rewards data
  backend/.gitignore
  backend/.nvmrc
  backend/package-lock.json
  backend/package.json
  backend/src/services/pools.ts
  backend/src/services/rewards.ts
  backend/src/services/user.ts
  backend/tsconfig.json
  frontend/.nvmrc
  frontend/package-lock.json
  frontend/package.json
  frontend/src/hooks/useGetRewardsSummary.ts
  frontend/src/pages/Rewards/Summary.tsx
Labels: 🔍 Ready for Review, size/L

#107 fix: updated node sdk import and config
  backend/src/services/rewards.ts
Labels: 🔍 Ready for Review, size/S

#108 Feat/store pooladdress
  backend/package-lock.json
  backend/src/controllers/v1/user.ts
  backend/src/data/migrations/20231206122920_user_rewards.ts
  backend/src/services/groups.ts
  backend/src/services/rewards.ts
  frontend/src/pages/Mint/CreateCollective.tsx
  frontend/src/pages/Rewards/ManageCollective.tsx
  frontend/src/services/ContractService.ts
Labels: 🔍 Ready for Review, size/L

#109 Feat/settop
  backend/package-lock.json
  backend/package.json
  backend/src/services/groups.ts
  backend/src/services/rewards.ts
  frontend/package-lock.json
  frontend/package.json
Labels: size/L

#110 chore: update sdk calls to use single sdk in backend
  backend/package-lock.json
  backend/package.json
  backend/src/services/rewards.ts
Labels: size/XS

#111 Feat/salt honeypot
  backend/package-lock.json
  backend/package.json
  backend/src/services/rewards.ts
  backend/src/utils/events-query/top-contributor-zora.ts
  frontend/package-lock.json
  frontend/package.json
Labels: 🔍 Ready for Review, size/S

#112 Feat/test flow
  backend/src/data/seeds/dev/1_user-groups-challenges.ts
  backend/src/services/pools.ts
  backend/src/services/rewards.ts
  backend/src/utils/events-query/top-contributor-zora.ts
  frontend/src/components/Mint/MintItemContent.tsx
Labels: size/L

#113 Feat/rewards route UI changes
  backend/src/data/migrations/20231206122920_user_rewards.ts
  backend/src/services/rewards.ts
  frontend/public/assets/icons/discover.svg
  frontend/public/assets/icons/discover_active.svg
  frontend/public/assets/icons/mint.svg
  frontend/public/assets/icons/mint_active.svg
  frontend/public/assets/icons/rewards.svg
  frontend/public/assets/icons/rewards_active.svg
  frontend/src/components/MenuIcon.tsx
  frontend/src/components/SideBarMenu.tsx
  frontend/src/components/TabsMenu.tsx
  frontend/src/theme/main.css
Labels: 🔍 Ready for Review, size/L

#114 Feat/UI tweaks
  frontend/src/components/Header.tsx
  frontend/src/components/OnboardingModal/index.tsx
  frontend/src/pages/Mint/CollectiveDetail/CollectiveChat.tsx
  frontend/src/pages/Mint/CollectiveDetail/CollectiveInfo.tsx
  frontend/src/pages/Mint/CollectiveDetail/CollectiveMint.tsx
  frontend/src/pages/Rewards/ManageCollective.tsx
  frontend/src/theme/main.css
Labels: 🔍 Ready for Review, size/L

#115 feat: updated controls for onboarding screens
  frontend/src/components/OnboardingModal/index.tsx
Labels: 🔍 Ready for Review, size/M

#116 Feat/test goerli
  backend/src/services/challenges.ts
  backend/src/services/rewards.ts
  backend/src/services/user.ts
  backend/src/utils/events-query/top-contributor-zora.ts
  frontend/src/pages/Mint/CollectiveDetail/CollectiveInfo.tsx
  frontend/src/pages/Rewards/Summary.tsx
Labels: 🔍 Ready for Review, size/L

#117 add honeypot balance check and success toast
  backend/src/services/rewards.ts
  frontend/src/components/Images/SwipeCard.tsx
  frontend/src/pages/Rewards/Summary.tsx
Labels: 🔍 Ready for Review, size/M

#118 cleanup
  backend/src/services/rewards.ts
  frontend/src/pages/Rewards/Summary.tsx
Labels: 🔍 Ready for Review, size/S

#119 Feat/creator flow
  backend/src/controllers/v1/challenges.ts
  backend/src/routes/v1/challenges.ts
  backend/src/services/challenges.ts
  frontend/src/components/Rewards/CreatorManagement.tsx
  frontend/src/hooks/useGetChallengesByCreator.tsx
  frontend/src/pages/Rewards/Summary.tsx
  frontend/src/services/ApiService.ts
Labels: 🔍 Ready for Review, size/L

#120 Feat/rewards claimed flag
  backend/src/data/migrations/20231206122920_user_rewards.ts
  backend/src/services/rewards.ts
  backend/src/services/user.ts
  frontend/src/pages/Mint/CollectiveDetail/CollectiveChat.tsx
Labels: 🔍 Ready for Review, ✅ Approved, size/M

#121 feat: added withdrawal validation
  backend/src/controllers/v1/user.ts
  backend/src/routes/v1/user.ts
  backend/src/services/rewards.ts
  backend/src/services/user.ts
  frontend/src/components/Mint/MintItemContent.tsx
  frontend/src/components/WithdrawalButton.tsx
  frontend/src/pages/Mint/NFTPage.tsx
  frontend/src/pages/Rewards/Summary.tsx
  frontend/src/services/ApiService.ts
Labels: 🔍 Ready for Review, size/XL

#122 Feat/fix sync
  backend/package-lock.json
  backend/package.json
  backend/src/data/seeds/dev/1_user-groups-challenges.ts
  backend/src/services/rewards.ts
  backend/src/services/user.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/hooks/useSignInWallet.ts
  frontend/src/pages/Rewards/Summary.tsx
  frontend/src/services/ContractService.ts
Labels: 🔍 Ready for Review, size/L

#123 Feat/invite mint
  frontend/src/App.tsx
  frontend/src/components/ConnectButton.tsx
  frontend/src/components/GenerateInvite.tsx
  frontend/src/components/Mint/MintItemContent.tsx
  frontend/src/components/Mint/MintItemResult.tsx
  frontend/src/types/mint.ts
Labels: 🔍 Ready for Review, size/M

#124 Feat/withdraw member
  backend/src/data/migrations/20231206122920_user_rewards.ts
  backend/src/services/rewards.ts
  frontend/src/components/ChallengesModal/InfoSheetModalMintActivity.tsx
  frontend/src/pages/Invite.tsx
  frontend/src/pages/Rewards/Summary.tsx
  frontend/src/services/ContractService.ts
Labels: 🔍 Ready for Review, size/L

#126 fix: changed main redirect
  frontend/src/App.tsx
Labels: size/XS, 🔍 Ready for Review

#127 fix: fixed mint modal state management
  frontend/src/components/ChallengesModal/ChallengeItemModal.tsx
  frontend/src/pages/Mint/CollectiveDetail/CollectiveMint.tsx
Labels: 🔍 Ready for Review, size/S

#128 Fix/handle is member invites
  frontend/src/components/PageTopBar.tsx
  frontend/src/components/TopBars/CollectiveTopBar.tsx
  frontend/src/components/TopBars/MintTopBar.tsx
  frontend/src/components/TopBars/RewardsTopBar.tsx
  frontend/src/pages/Discover/Discover.tsx
  frontend/src/pages/Discover/New.tsx
  frontend/src/pages/Invite.tsx
  frontend/src/services/ContractService.ts
Labels: 🔍 Ready for Review, size/XL

#129 fix: added hook to read the current connector from wagmi and send to …
  frontend/src/App.tsx
  frontend/src/components/ConnectButton.tsx
  frontend/src/hooks/useAccountConnector.ts
  frontend/src/pages/Rewards/ManageCollective.tsx
  frontend/src/services/ContractService.ts
Labels: 🔍 Ready for Review, size/M

#130 Bugfix/mint routing
  backend/src/controllers/v1/groups.ts
  backend/src/controllers/v1/user.ts
  backend/src/services/rewards.ts
  backend/src/services/user.ts
  frontend/src/components/ConnectButton.tsx
  frontend/src/components/Header.tsx
  frontend/src/pages/Mint/CollectiveDetail/CollectiveChat.tsx
  frontend/src/pages/Mint/Mint.tsx
Labels: 🔍 Ready for Review, size/L

#131 Feat/improve swip cards
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/ChallengesModal/ChallengeImageCard.tsx
  frontend/src/components/ChallengesModal/ChallengeItemMintModal.tsx
  frontend/src/components/ChallengesModal/ChallengeItemModal.tsx
  frontend/src/pages/Mint/CollectiveDetail/CollectiveMint.tsx
  frontend/src/theme/main.css
Labels: ✅ Approved, size/L
